name: My Second CI

on: 
  push:
    branches: ["main"]

jobs:
  test-run: 
    runs-on: ubuntu-latest

    steps:
      - name : Say Hello
        run : echo "Github Actions 테스트가 성공적으로 실행 되었습니다."

      - name: Check OS Info
        run: cat /etc/os-release
    
